{
 "title": "Telegraf: system dashboard",
 "description": "InfluxDB dashboards for telegraf metrics",
 "tags": [
  "influxdb",
  "telegraf"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "postgres" },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "host",
    "label": "host",
    "query": "SELECT DISTINCT host FROM cpu order by host asc;"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "SELECT DISTINCT path FROM disk;"
   },
   { "name": "cpu", "label": "CPU", "query": "SELECT DISTINCT cpu FROM cpu ;" },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SELECT DISTINCT name FROM diskio;"
   },
   {
    "name": "netif",
    "label": "Network interface",
    "query": "SELECT DISTINCT interface  FROM net;"
   }
  ]
 },
 "panels": [
  {
   "title": "Quick overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  last(uptime),\r\n  host\r\nFROM\r\n  \"system\"\r\nWHERE\r\n  uptime > 0\r\n  AND $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "LA medium",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  last(load5),\r\n  host\r\nFROM\r\n  \"system\"\r\nWHERE\r\n  load5 > 0\r\n  AND $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Zombies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  last(zombies),\r\n  host\r\nFROM\r\n  \"processes\"\r\nWHERE\r\n  zombies > 0\r\n  AND $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  last(total),\r\n  host\r\nFROM\r\n  \"processes\"\r\nWHERE\r\n  total > 0\r\n  AND $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  last(total_threads),\r\n  host\r\nFROM\r\n  \"processes\"\r\nWHERE\r\n  total_threads > 0\r\n  AND $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  last(usage_idle) * -1 + 100,\r\n  host\r\nFROM\r\n  \"cpu\"\r\nWHERE\r\n  usage_idle > 0\r\n  AND \"cpu\" = 'cpu-total'\r\n  AND $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  last(used_percent),\r\n  host\r\nFROM\r\n  \"mem\"\r\nWHERE\r\n  used_percent > 0\r\n  AND $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  last(used_percent),\r\n  host\r\nFROM\r\n  \"swap\"\r\nWHERE\r\n  used_percent > 0\r\n  AND $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "RootFS used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  last(used_percent),\r\n  host\r\nFROM\r\n  \"disk\"\r\nWHERE\r\n  used_percent > 0\r\n  AND \"path\" = '/'\r\n  AND $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  last(usage_iowait),\r\n  host\r\nFROM\r\n  \"cpu\"\r\nWHERE\r\n  usage_iowait > 0\r\n  AND \"cpu\" = 'cpu-total'\r\n  AND $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(usage_user) as user,\r\n  avg(usage_system) as \"system\",\r\n  avg(usage_softirq) as \"softirq\",\r\n  avg(usage_steal) as \"steal\",\r\n  avg(usage_nice) as \"nice\",\r\n  avg(usage_irq) as \"irq\",\r\n  avg(usage_iowait) as \"iowait\",\r\n  avg(usage_guest) as \"guest\",\r\n  avg(usage_guest_nice) as \"guest_nice\",\r\n  host\r\nFROM\r\n  \"cpu\"\r\nWHERE\r\n  cpu = 'cpu-total'\r\n  AND $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Load averages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(load1) as short,\r\n  avg(load5) as medium,\r\n  avg(load15) as long,\r\n  host\r\nFROM\r\n  \"system\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(running) as running,\r\n  avg(blocked) as blocked,\r\n  avg(sleeping) as sleeping,\r\n  avg(stopped) as stopped,\r\n  avg(zombies) as zombies,\r\n  avg(paging) as paging,\r\n  avg(unknown) as unknown,\r\n  host\r\nFROM\r\n  \"processes\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(total) as total,\r\n  avg(used) as used,\r\n  avg(cached) as cached,\r\n  avg(free) as free,\r\n  avg(buffered) as buffered,\r\n  host\r\nFROM\r\n  \"mem\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Context switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(context_switches) as \"context switches\",\r\n  host\r\nFROM\r\n  \"kernel\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(processes_forked) as forks,\r\n  host\r\nFROM\r\n  \"kernel\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(\"filemax\") as max,\r\n  host\r\nFROM\r\n  \"linux_sysctl_fs\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(\"total\"),\r\n  host\r\nFROM\r\n  \"interrupts\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  \"irq\",\r\n  host"
    }
   ]
  },
  {
   "title": "Per-cpu usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU usage for $cpu",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
     "repeat": "cpu",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(usage_user) as \"user\",\r\n  avg(usage_system) as \"system\",\r\n  avg(usage_softirq) as \"softirq\",\r\n  avg(usage_steal) as \"steal\",\r\n  avg(usage_nice) as \"nice\",\r\n  avg(usage_irq) as \"irq\",\r\n  avg(usage_iowait) as \"iowait\",\r\n  avg(usage_guest) as \"guest\",\r\n  avg(usage_guest_nice) as \"guest_nice\"\r\nFROM\r\n  \"cpu\"\r\nWHERE\r\n  $__timeFilter(timestamp) and cpu = ($cpu)\r\nGROUP by\r\n  timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Conntrack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Netfilter conntrack usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(ip_conntrack_count),\r\n  host\r\nFROM\r\n  \"conntrack\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Network stack (TCP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TCP connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(tcp_close) as CLOSED,\r\n  avg(tcp_close_wait) as CLOSE_WAIT,\r\n  avg(tcp_closing) as CLOSING,\r\n  avg(tcp_established) as ESTABLISHED,\r\n  avg(tcp_fin_wait1) as FIN_WAIT1,\r\n  avg(tcp_fin_wait2) as FIN_WAIT2,\r\n  avg(tcp_last_ack) as LAST_ACK,\r\n  avg(tcp_syn_recv) as SYN_RECV,\r\n  avg(tcp_syn_sent) as SYN_SENT,\r\n  avg(tcp_time_wait) as TIME_WAIT,\r\n  host\r\nFROM\r\n  netstat\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP BY\r\n  timestamp,\r\n  host"
    },
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(tcp_estabresets)\r\nFROM\r\n  \"net\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\nGROUP by\r\n  timestamp"
    }
   ]
  },
  {
   "title": "TCP aborts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(\"TcpExtTCPAbortOnClose\") as TcpExtTCPAbortOnClose,\r\n  avg(\"TcpExtTCPAbortOnData\") as TcpExtTCPAbortOnData,\r\n  avg(\"TcpExtTCPAbortOnTimeout\") as TcpExtTCPAbortOnTimeout,\r\n  avg(\"TcpExtTCPAbortFailed\") as TcpExtTCPAbortFailed,\r\n  avg(\"TcpExtTCPAbortOnLinger\") as TcpExtTCPAbortOnLinger,\r\n  avg(\"TcpExtTCPAbortOnMemory\") as TcpExtTCPAbortOnMemory,\r\n  host\r\nFROM\r\n  \"nstat\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "TCP handshake issues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(tcp_estabresets) as tcp_estabresets,\r\n  avg(tcp_outrsts) as tcp_outrsts,\r\n  avg(tcp_activeopens) as tcp_activeopens,\r\n  avg(tcp_passiveopens) as tcp_passiveopens,\r\n  host\r\nFROM\r\n  \"net\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "TCP SYN cookies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(\"TcpExtSyncookiesFailed\") as failed,\r\n  avg(\"TcpExtSyncookiesRecv\") as received,\r\n  avg(\"TcpExtSyncookiesSent\") as sent,\r\n  host\r\nFROM\r\n  \"nstat\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "ICMP packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 81 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(\"IcmpInEchos\") as \"in echos\",\r\n  avg(\"IcmpOutEchos\") as \"out echos\",\r\n  avg(\"IcmpInEchoReps\") as \"in echo responses\",\r\n  avg(\"IcmpOutEchoReps\") as \"out echo responses\",\r\n  host\r\nFROM\r\n  \"nstat\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "ICMP errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(\"IcmpInErrors\") as \"in errors\",\r\n  avg(\"IcmpOutErrors\") as \"out errors\",\r\n  avg(\"IcmpInCsumErrors\") as \"checksum errors\",\r\n  host\r\nFROM\r\n  \"nstat\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "IPv4 errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(\"IpInDiscards\") as \"in discards\",\r\n  avg(\"IpOutDiscards\") as \"out discards\",\r\n  avg(\"IpInHdrErrors\") as \"in hdr errors\",\r\n  avg(\"IpInAddrErrors\") as \"in addr errors\",\r\n  avg(\"IpOutNoRoutes\") as \"out no routes\",\r\n  avg(\"IpInUnknownProtos\") as \"in unknown protocol\",\r\n  host\r\nFROM\r\n  \"nstat\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "IPv6 errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(\"Ip6InDiscards\") as \"in discards\",\r\n  avg(\"Ip6OutDiscards\") as \"out discards\",\r\n  avg(\"Ip6InHdrErrors\") as \"in hdr errors\",\r\n  avg(\"Ip6InAddrErrors\") as \"in addr errors\",\r\n  avg(\"Ip6OutNoRoutes\") as \"out no routes\",\r\n  avg(\"Ip6InUnknownProtos\") as \"in unknown protocol\",\r\n  host\r\nFROM\r\n  \"nstat\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Network stack (UDP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {}
   ]
  },
  {
   "title": "UDP datagrams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(udp_indatagrams) as \"in datagrams\",\r\n  avg(udp_outdatagrams) as \"out datagrams\",\r\n  host\r\nFROM\r\n  \"net\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "UDP buffer errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(\"UdpSndbufErrors\") as \"Send buffer errors\",\r\n  avg(\"UdpRcvbufErrors\") as \"Receive buffer errors\",\r\n  host\r\nFROM\r\n  \"nstat\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "UDP errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(\"UdpInCsumErrors\") as \"checksum errors\",\r\n  avg(\"UdpInErrors\") as \"in errors\",\r\n  avg(\"UdpNoPorts\") as \"no ports\",\r\n  host\r\nFROM\r\n  \"nstat\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Network interface stats for $netif",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "repeat": "netif",
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(bytes_recv) * 8 as \"in\",\r\n  avg(bytes_sent) * 8 as \"out\",\r\n  host\r\nFROM\r\n  \"net\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND interface ~ ($netif)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(packets_recv) as \"in\",\r\n  avg(packets_sent) as \"out\",\r\n  host\r\nFROM\r\n  \"net\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND interface ~ ($netif)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Network drops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "pps", "label": "Drops per second" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(drop_in) as \"in\",\r\n  avg(drop_out) as \"out\",\r\n  host\r\nFROM\r\n  \"net\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND interface ~ ($netif)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Network errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "short", "label": "Errors per second" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(err_in) as \"in\",\r\n  avg(err_out) as \"out\",\r\n  host\r\nFROM\r\n  \"net\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND interface ~ ($netif)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Swap I/O bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(\"in\") as \"in\",\r\n  avg(\"out\") as \"out\",\r\n  host\r\nFROM\r\n  \"swap\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Swap usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 141 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(used) as \"used\",\r\n  avg(total) as \"total\",\r\n  host\r\nFROM\r\n  \"swap\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Disk IOPS for /dev/$disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 },
   "repeat": "disk",
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk I/O requests for /dev/$disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(reads) as \"read\",\r\n  avg(writes) as \"write\",\r\n  host\r\nFROM\r\n  \"diskio\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND \"name\" ~ ($disk)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Disk I/O bytes for /dev/$disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 149 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(read_bytes) as \"read\",\r\n  avg(write_bytes) as \"write\",\r\n  host\r\nFROM\r\n  \"diskio\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND \"name\" ~ ($disk)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Disk I/O time for /dev/$disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 149 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(read_time) as \"read\",\r\n  avg(write_time) as \"write\",\r\n  host\r\nFROM\r\n  \"diskio\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND \"name\" ~ ($disk)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Disk space usage for $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 164 },
   "repeat": "mountpoint",
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk usage for $mountpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 165 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(total) AS \"total\",\r\n  avg(used) as \"used\",\r\n  host\r\nFROM\r\n  \"disk\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND \"path\" ~ ($mountpoint)     AND host = ('$host')\r\n\r\nGROUP by\r\n  timestamp,\r\n  path,\r\n  host"
    }
   ]
  },
  {
   "title": "Disk inodes for $mountpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 165 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(inodes_used) as \"used\",\r\n  avg(inodes_free) + avg(inodes_used) as \"total\",\r\n  host\r\nFROM\r\n  \"disk\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host,\r\n  path"
    }
   ]
  },
  {
   "title": "Metrics velocity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 212 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Delivery time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 213 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(\"write_time_ns\"),\r\n  host\r\nFROM\r\n  \"internal_write\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND host = ('$host')\r\nGROUP by\r\n  timestamp,\r\n  host"
    }
   ]
  },
  {
   "title": "Gather time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 213 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(\"gather_time_ns\")\r\nFROM\r\n  \"internal_gather\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\nGROUP by\r\n  timestamp"
    }
   ]
  },
  {
   "title": "Written metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 213 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  avg(\"metrics_written\")\r\nFROM\r\n  \"internal_agent\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\nGROUP by\r\n  timestamp"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 213 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\navg(\"gather_errors\") as \"Gather errors\",\r\navg(\"metrics_dropped\") as \"Dropped metrics\"\r\n\r\nFROM\r\n  \"internal_agent\"\r\nWHERE\r\n  $__timeFilter(timestamp)\r\nGROUP by\r\n  timestamp"
    }
   ]
  }
 ]
}